/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.icecondor.nest;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int grid_set_menu_radar=0x7f050001;
        public static final int grid_set_menu_settings=0x7f050004;
        public static final int ibtn_settings_pigeon_on=0x7f050005;
        public static final int radar_close_list=0x7f050003;
        public static final int radar_lat=0x7f050002;
        public static final int th_set_menu_tabhost=0x7f050000;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040002;
        public static final int hello=0x7f040001;
        public static final int menu_version=0x7f040000;
        public static final int settings_transmitting=0x7f040005;
        public static final int tab_title1=0x7f040003;
        public static final int tab_title2=0x7f040004;
    }
}
